language: php
php:
  - 5.5
  - 5.6
  - hhvm
  - nightly

before_install:
  - pip install --user codecov

before_script: composer install -n

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - codecov
