language: php
php:
  - 5.5
  - 5.6
  - hhvm
  - nightly

before_script: composer install -n
before_script: composer require satooshi/php-coveralls --dev

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit --coverage-clover=build/logs/clover.xml
